# fly.toml app configuration file generated for habitual-ai on 2025-06-17T08:12:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'habitual-ai'
primary_region = 'arn'

[build]

[processes]
  app = "python bot/bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
