# fly.toml app configuration file generated for habitual-ai
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'habitual-ai'
primary_region = 'iad'

[build]

[env]
  # These will be set via fly secrets
  
[processes]
  app = "python bot/bot.py"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024